#!/bin/sh
#
# Generate alert reminders per .reminders file 
### VARS
DIMX=1440
POSY=440
TIM=10

### CODE
remind -z -k"echo %s | dzen2 -bg black -fg cyan -w $DIMX -x $DIMX -y $POSY -p $TIM &" /home/rockwolf/.reminders_schedule &
remind -z -k"echo %s | dzen2 -bg red -fg white -w $DIMX -x $DIMX -y $POSY -p $TIM &" /home/rockwolf/.reminders_events &
remind -z -k"echo %s | dzen2 -bg white -fg blue -w $DIMX -x $DIMX -y $POSY -p $TIM &" /home/rockwolf/.reminders_nhl &
