#!/bin/sh
#
# Author: rockwolf
# Date: 2010-12-29
# 
# Creates a backup of the dev dir
#

DIR=/home/rockwolf/dev

fBackupWeekly()
{
    OLDDIR=/mnt/D/bak/dev/weekly/old
    NEWDIR=/mnt/D/bak/dev/weekly/new
    
    fBackup $OLDDIR $NEWDIR
    echo "dev - weekly backup [OK]"
}

fBackup()
{
    ### remove previous bak-ups
    rm $OLDDIR/*.tar.gz

    ### move current backup from new to old
    mv $NEWDIR/*.tar.gz $OLDDIR

    ### make backup
    tar czf $NEWDIR/dev`date +%Y-%m-%d`.tar.gz $DIR
}

fBackupMonthly()
{
    OLDDIR=/mnt/D/bak/dev/monthly/old
    NEWDIR=/mnt/D/bak/dev/monthly/new
    
    fBackup $OLDDIR $NEWDIR
    echo "dev - monthly backup [OK]"
}


fUsage()
{
    echo "Usage: bu-dev"
    exit 1
}

case $# in
0)
    DOW=`date +%u`
    DOM=`date +%d`
    if [ "$DOW" = "1" ];
    then
        fBackupWeekly
    fi
    if [ "$DOM" = "01" ];
    then
        fBackupMonthly
    fi
    ;;
*)
    fUsage
    ;;
esac
