#!/bin/sh
#
# Author: rockwolf
# Date: 2010-12-29
# 
# Creates a backup of the db on evy
#
# All
# ---
# backup: pg_dumpall -U postgres -h <host> -f <output.bak>
# restore: psql -U postgres -h <host> -f <output.bak> template1
#
# Single DB
# ---------
# backup 1 db: pg_dump -U postgres -h <host> -F c -f <output.bak> <dbname>
# restore: createdb -U postgres -h <host> <newdbname>
#          pg_restore -U postgres -h <host> -d <newdbname> <output.bak>
#

fBackupDaily()
{
    HOST=$1
    OLDDIR=/mnt/D/bak/db/$HOST/daily/old
    NEWDIR=/mnt/D/bak/db/$HOST/daily/new
    
    fBackup $HOST $OLDDIR $NEWDIR
    echo "db - daily backup [OK]"
}

fBackup()
{
    ### remove previous bak-ups
    rm $OLDDIR/*.tar.gz

    ### move current backup from new to old
    mv $NEWDIR/*.tar.gz $OLDDIR

    ### make backup
    pg_dumpall -U postgres -h $HOST -f $NEWDIR/$HOST`date +%Y-%m-%d`.bak
    tar czf $NEWDIR/$HOST`date +%Y-%m-%d`.tar.gz $NEWDIR/$HOST`date +%Y-%m-%d`.bak
    # only keep compressed file
    rm $NEWDIR/$HOST`date +%Y-%m-%d`.bak   
}

fBackupMonthly()
{
    HOST=$1
    OLDDIR=/mnt/D/bak/db/$HOST/monthly/old
    NEWDIR=/mnt/D/bak/db/$HOST/monthly/new
    
    fBackup $HOST $OLDDIR $NEWDIR
    echo "db - monthly backup [OK]"
}


fUsage()
{
    echo "Usage: bu-db <hostname>"
    exit 1
}

case $# in
1)
    DOM=`date +%d`
    fBackupDaily $1
    if [ "$DOM" = "01" ];
    then
        fBackupMonthly $1
    fi
    ;;
*)
    fUsage
    ;;
esac
