#!/bin/sh
#
# Author: rockwolf
# Date: 2010-12-29
# 
# Creates a backup of the clipf dir
#

DIR=/home/rockwolf/.config/clipf

fBackupDaily()
{
    OLDDIR=/mnt/D/bak/pf/daily/old
    NEWDIR=/mnt/D/bak/pf/daily/new
    
    fBackup $OLDDIR $NEWDIR
    echo "pf - daily backup [OK]" 
}

fBackupWeekly()
{
    OLDDIR=/mnt/D/bak/pf/weekly/old
    NEWDIR=/mnt/D/bak/pf/weekly/new
    
    fBackup $OLDDIR $NEWDIR
    echo "pf - weekly backup [OK]" 
}

fBackup()
{
    ### remove previous bak-ups
    rm $OLDDIR/*.tar.gz

    ### move current backup from new to old
    mv $NEWDIR/*.tar.gz $OLDDIR

    ### make backup
    tar czf $NEWDIR/pf`date +%Y-%m-%d`.tar.gz $DIR
}

fBackupMonthly()
{
    OLDDIR=/mnt/D/bak/pf/monthly/old
    NEWDIR=/mnt/D/bak/pf/monthly/new
    
    fBackup $OLDDIR $NEWDIR
    echo "pf - monthly backup [OK]" 
}


fUsage()
{
    echo "Usage: bu-pf"
    exit 1
}

case $# in
0)
    DOW=`date +%u`
    DOM=`date +%d`
    fBackupDaily
    if [ "$DOW" = "1" ];
    then
        fBackupWeekly
    fi
    if [ "$DOM" = "01" ];
    then
        fBackupMonthly
    fi
    ;;
*)
    fUsage
    ;;
esac
