#!/bin/sh
#
# Author: rockwolf
# Date: 2010-12-29
# 
# Creates a backup of the VM's
# and hidden data files
#

DIR=/home/rockwolf/.VirtualBox

fBackupWeekly()
{
    OLDDIR=/mnt/D/bak/vm/weekly/old
    NEWDIR=/mnt/D/bak/vm/weekly/new
    
    fBackup $OLDDIR $NEWDIR
    echo "vm - weekly backup [OK]"
}

fBackup()
{
    ### remove previous bak-ups
    rm $OLDDIR/*.tar.gz

    ### move current backup from new to old
    mv $NEWDIR/*.tar.gz $OLDDIR

    ### make backup
    tar czf $NEWDIR/vm`date +%Y-%m-%d`.tar.gz $DIR
}

fBackupMonthly()
{
    OLDDIR=/mnt/D/bak/vm/monthly/old
    NEWDIR=/mnt/D/bak/vm/monthly/new
    
    fBackup $OLDDIR $NEWDIR
    echo "vm - monthly backup [OK]"
}


fUsage()
{
    echo "Usage: bu-vm"
    exit 1
}

case $# in
0)
    DOW=`date +%u`
    DOM=`date +%d`
    if [ "$DOW" = "1" ];
    then
        fBackupWeekly
    fi
    if [ "$DOM" = "01" ];
    then
        fBackupMonthly
    fi
    ;;
*)
    fUsage
    ;;
esac
