#!/bin/sh
#
# commre: Communication's Regular Expression
# Author: Andy Nagels
# Date: 2010-12-09
#
# This script was designed to be used with
# the irc client ii (http://tools.suckless.org/ii)
# Scans for lines in output files of ii

### VARIABLES ###
# Here, you can set the output file
OUTFILE="/var/log/im.log" 
# this is a temporay file that is needed while
# running the script, it's automatically deleted
# when the script finishes
# default: <scriptname>.tmp
TMPFILE="/var/tmp/commre$$.tmp" #${0//[^[:alnum:]]/}.tmp" 
# your ii irc folder
IIMAIN=$HOME/irc
# here you can set regular expressions to look for in
# specific files
#
# REGEXP1: it may not include the string <TEST>
# REGEXP2: it must contain either test, Test, TEST, teSt or set
# REGEXPCOMBO: a trick to combine them both and execute them on outfiles
REGEXP1="<rockwolf>|has joined|Welcome to the|= &bitlbee|= #|changed mode/|changed nick to|* #"
#REGEXP1="<rockwolf>|has joined|Welcome to the|= &bitlbee|= #|changed mode/|changed nick to|* #"
REGEXP2="(rock|ROCK|ROck|roCK|RocK|rOCk|rOCK|RoCK|ROcK|ROCk|RoCk|rOcK|Rock|rOck|roCk|rocK)"

### MAIN CODE ###
#echo "Find data based on regular expressions..."
#echo "$REGEXP2"
#echo "$REGEXP1"
egrep -H $REGEXP2 $IIMAIN/*/out $IIMAIN/*/*/out > $TMPFILE 
#echo ${`
#egrep -vh "<rockwolf>|has joined|Welcome to the|= &bitlbee|= #|changed mode/|changed nick to|* #|Mattdoesrock" $TMPFILE #> $TMPFILE
#`// /}
RES=`egrep -vh "<rockwolf>|has joined|Welcome to the|= &bitlbee|= #|changed mode/|changed nick to|* #|Mattdoesrock" $TMPFILE` #> $TMPFILE
RESF=${RES//$IIMAIN/}
RES=${RESF//"/out"}
echo $RES
#echo "Remove temporary file..."
rm $TMPFILE
#echo "Done."
