#!/bin/bash

# config
BGCOLOR="black"
FGCOLOR="CYAN"
XPOS=0
YPOS=785
BEHAVIOR='sigusr1=raise;sigusr2=lower;onexit=exec:rm /tmp/dzen2-pid;button3=exit' 

echo "$1" |
dzen2 -fn '-*-aqui-*-*-*-*-*-*-*-*-*-*-*' -bg $BGCOLOR -fg $FGCOLOR -ta l -x $XPOS -y $YPOS -p -e $BEHAVIOUR & echo $! > /tmp/dzen2-pid
