#!/bin/sh
# Author: Rockwolf 
# Date: 07/02/2008
# Show new mails from maildirtree output...

## config vars ##
MAIL=/home/rockwolf/doc/MuttMail/

### NO NEED TO EDIT BEYOND THIS POINT ###
## usage error ##
if [ ! $# == 1 ]; then
	echo "Usage: $0 <Maildir number> : show unread mails for Maildir"
    	#echo -n "       $0 -s<Maildir number> : show unread mails for Maildir in short mode"
    	echo -n "       $0 -l : list available Maildir folders"
	exit
fi

## get maildirs ##
count=0

for i in $(ls $MAIL | grep mail); do
	arr[$count]=$i
	let count++
done

num=$[$1-1]

if [ "$1" = "0" ]; then
	echo "Error: 0 is not a valid mailbox number."
	echo "Usage: $0 <Maildir number> : show unread mails for Maildir"
    	#echo -n "       $0 -s<Maildir number> : show unread mails for Maildir in short mode"
    	echo -n "       $0 -l : list available Maildir folders"
	exit
elif [ "$1" = "-l" ]; then
	# als optie -l => list mailboxes
	echo "Current mailboxes"
	echo "-----------------"
	i=1
	for arr in ${arr[@]}
	do
		echo -n "$i : "
		echo $arr
		let i++
	done
	exit
elif [ "${arr[$num]}" != "" ]; then
	MBOX="${arr[$num]}"

else
	echo "Usage: $0 <Maildir number> : show unread mails for Maildir"
    	#echo -n "       $0 -s<Maildir number> : show unread mails for Maildir in short mode"
    	echo -n "       $0 -l : list available Maildir folders"
	exit
fi

## core script ##
#execute maildirtree on maildir folder
MDT=`maildirtree $MAIL/$MBOX`
#show all lines with new mail + total

#todo: implement:
#mdt 2 |grep messages | cut -d' ' -f1-2
echo "$MDT" | grep -v "(0/"

