#!/bin/sh

MINARGS=1          # Script requires at least two arguments.
E_BADARGS=65
#pl1="home_dhcp"
#pl2="home_static"
#pl3="other_nowless"
#pl4="other_wless"

show_error(){
echo
#echo 'Error in script usage: mscreen <type> <1 or 2 monitors>'
echo 'Error in script usage: mscreen <1 or 2 monitors>'
#echo 'Possible type are:'
#echo $pl1
#echo $pl2
#echo $pl3
#echo $pl4
echo
exit $E_BADARGS
}

# Checks number of arguments.
if [[ $# -gt $MINARGS ||  $# -lt $MINARGS ]];
then
show_error
fi

place=$1

#echo "Network settings:"
#if [ $place == $pl1 ]
#then
#	echo
#	echo "Using dhcp to get an ip for eth0..."
#	rm -i /etc/conf.d/net
#	echo ">>> update conf.d/net"
#	ln -s /etc/conf.d/net_dhcp /etc/conf.d/net
#	echo ">>> start eth0"
#	/etc/init.d/net.eth0 start
#elif [ $place == $pl2 ]
#then
#	echo
#	echo "Not using dhcp to get an ip for eth0..."
#	rm -i /etc/conf.d/net
#	echo ">>> update conf.d/net\n"
#	ln -s /etc/conf.d/net_static /etc/conf.d/net
#	echo ">>> start eth0\n"
#	/etc/init.d/net.eth0 start
#elif [ $place == $pl3 ]
#then
#	echo
#	echo "Wireless should not be available, eth1 will not be used..."
#	echo "Eth0 gets a static ip..."
#	rm -i /etc/conf.d/net
#	echo ">>> update conf.d/net\n"
#	ln -s /etc/conf.d/net_school /etc/conf.d/net
#	echo ">>> start eth0\n"
#	/etc/init.d/net.eth0 start
#elif [ $place == $pl4 ]
#then
#	echo
#	echo "Wireless should be available, I will try to use eth1..."
#	echo "Eth0 gets a static ip..."
#	echo "Using dhcp to get an ip for eth1..."
#	rm -i /etc/conf.d/net
#	echo ">>> update conf.d/net\n"
#	ln -s /etc/conf.d/net_school /etc/conf.d/net
#	#echo ">>> start eth0\n"
#	#/etc/init.d/net.eth0 start
#	echo ">>> start eth1\n"
#	/etc/init.d/net.eth1 start
#else
#	show_error
#fi

mon=$1

echo "Xorg settings:"
if [ $# -ne 1 ]
then
		echo "Keeping current monitor settings..."
else
	if [ $mon -eq 2 ]
	then
		echo
		echo "I will try to use the external monitor..."
		echo  ">>> removing symbolic link xorg.conf"
		rm -i /etc/X11/xorg.conf
		echo  ">>> we will be using xorg_xinerama"
		ln -s /etc/X11/xorg_xinerama.conf /etc/X11/xorg.conf
	elif [ $mon -eq 1 ]
	then
		echo
		echo "I will not use an external monitor..."
		echo  ">>> removing symbolic link xorg.conf"
		rm -i /etc/X11/xorg.conf
		echo  ">>> we will be using xorg_backup"
		ln -s /etc/X11/xorg_backup.conf /etc/X11/xorg.conf
	else
		show_error
	fi	
	echo "Done."
fi
