#!/bin/sh

echo

#spaces in filenames => underscores
echo "Converting spaces in filenames..."
for i in *.mp3; do mv "$i" `echo $i | tr ' ' '_'`; done

#everything lowercase
#for i in *.[Mm][Pp]3; do mv "$i" `echo $i | tr '[A-Z]' '[a-z]'`; done

#just the extensions lowercase (.MP3 => .mp3)
echo "Converting MP3 extensions to lowercase..."
for i in *.MP3; do mv "$i" "`basename "$i" .MP3`.mp3"; done

#convert mp3 to wav
echo "Decoding  mp3-files to wav-files"
for i in *.mp3; do mpg123 -w "`basename "$i" .mp3`.wav" "$i"; done

#check the files: 44.1kHz, 16 bit or convert to the correct format with sox:
echo "You should check the files now... Skipping this step"
#sox track01.wav -r 44100 track01-new.wav resample

#normalize (same volume level)
echo "Normalizing files..."
normalize -m *.wav

#create toc file
echo "Creating toc file"
tocgen -t cd.toc

echo "Done."
echo
