#!/bin/sh

#TODO: remove -R from options and execute commre in crontab
# write (>) results in file (/var/log/im.log) + monitor with regular -f
# GUI
multitail -cS irc -s 2 -sn 4,4 \
-t "bitlbee" -f $HOME/irc/localhost/out \
-t "quakenet" -f $HOME/irc/irc.quakenet.org/out \
-t "irc.oftc.net" -f $HOME/irc/irc.oftc.net/out \
-t "im" -f ~/.irssi/fnotify \
-t "&bitlbee" -f $HOME/irc/localhost/\&bitlbee/out \
-t "#ra-chan" -f $HOME/irc/irc.quakenet.org/\#regnum-online/out \
-t "#dummy" -f $HOME/irc/localhost/lordazus/out

#-R 2 -l 'egrep "^(<rockwolf>)(rock|ROCK|ROck|roCK|RocK|rOCk|rOCK|RoCK|ROcK|ROCk|RoCk|rOcK|Rock|rOck|roCk|rocK)" $HOME/irc/*/*/out' \
#-t "chat.be" -f $HOME/irc/irc.chat.be/out \
#-t "#telenet.20" -f $HOME/irc/irc.chat.be/\#telenet.20/out \
