#!/bin/sh
#

WALLDIR=/home/rockwolf/arc/img/wall/nihongo
#OTHERDIR=/home/rockwolf/.earthwallpaper
OTHERDIR=/home/rockwolf/arc/img/wall/multidisplay/
PACDIR=/home/rockwolf/doc/current/wallpapers/pacgraph

#cd $PACDIR && pacgraph -b black -l white -t cyan

###sleep 6 && DISPLAY=:0.1 /usr/bin/feh --bg-center $OTHERDIR/hokkaidobridge.jpg
#rosescostabravawideRnormal.jpg
#world_sunlight_Wallpaper.jpg
#bleach/1_Ikakku_Bankai_by_Last_of_the_Arrancar.jpg
#/naruto/Hinata2.jpg
###DISPLAY=:0.0 /usr/bin/feh --bg-center $WALLDIR/hokkaidoflowers.jpg
#kaley-kaley-cuoco-487066_1920_1200.jpg
#5_1440_900.jpg
#rosescostabravawideLnormal.jpg
#DISPLAY=:0.0 /usr/bin/feh --bg-scale $PACDIR/pacgraph.png
#$WALLDIR/panoramic/rosescostabravawideR.jpg
#bleach/1_kyorakushunsuiqe2.jpg
#bleach/yoruichi.jpg

#DISPLAY=:0.0 /usr/bin/feh --bg-scale $OTHERDIR/dreamforest_3360x1050.jpg
/usr/bin/feh --bg-scale $OTHERDIR/rosescostabrava.jpg
#DISPLAY=:0.1 /usr/bin/feh --bg-scale $WALLDIR/Hokkaido3.jpg
#DISPLAY=:0.1 /usr/bin/feh --bg-scale $OTHERDIR/1440_900_20091116100708821363.jpg
#Shore22880x900.jpg
#Super_Mario_3_Dual_by_charlesdyer.png
