#!/bin/sh
#
# Author: rockwolf
# Date: 2014-03-03
# 
# Creates a backup of the prd dir
#

DIR=/home/rockwolf/nintai
PREFIX=/mnt/bak
NAME=nintai

fBackupDaily()
{
    OLDDIR=$PREFIX/daily/old
    NEWDIR=$PREFIX/daily/new
    
    fClearBackup $OLDDIR $NEWDIR
    echo $NAME"- daily backup [OK]"
    
    ### make backup
    tar czf $NEWDIR/$NAME`date +%Y-%m-%d`.tar.gz $DIR
}

fBackupWeekly()
{
    OLDDIR=$PREFIX/weekly/old
    NEWDIR=$PREFIX/weekly/new
    
    fClearBackup $OLDDIR $NEWDIR
    echo $NAME"- weekly backup [OK]"
    
    ### make backup
    tar czf $NEWDIR/$NAME`date +%Y-%m-%d`.tar.gz $DIR
}

fBackupMonthly()
{
    OLDDIR=$PREFIX/monthly/old
    NEWDIR=$PREFIX/monthly/new
    
    fClearBackup $OLDDIR $NEWDIR
    echo $NAME" - monthly backup [OK]"
    
    ### make backup
    tar czf $NEWDIR/$NAME`date +%Y-%m-%d`.tar.gz $DIR
}

fClearBackup()
{
    ### remove previous bak-ups
    rm $OLDDIR/*.tar.gz

    ### move current backup from new to old
    mv $NEWDIR/*.tar.gz $OLDDIR
}

fUsage()
{
    echo "Usage: bu-prd"
    exit 1
}

case $# in
0)
    fBackupDaily
    DOW=`date +%u`
    DOM=`date +%d`
    if [ "$DOW" = "1" ];
    then
        fBackupWeekly
    fi
    if [ "$DOM" = "01" ];
    then
        fBackupMonthly
    fi
    ;;
*)
    fUsage
    ;;
esac
