#!/bin/sh
#
# Author: rockwolf
# Date: 2010-12-29
# 
# Creates a backup of the config files
# and hidden data files
#

C01=/home/rockwolf/\.[a-zA-Z]*rc
C02=/home/rockwolf/\.vim*
C03=/home/rockwolf/\.mc
C04=/home/rockwolf/\.local
C05=/home/rockwolf/\.gnupg
C06=/home/rockwolf/\.fonts.conf.d
C07=/home/rockwolf/\.config
C08=/home/rockwolf/\.cmus
C09=/home/rockwolf/\.authenticate
C10=/home/rockwolf/\.abook
C11=/home/rockwolf/\.Xresources
C12=/home/rockwolf/\.xinitrc
C13=/home/rockwolf/\.reminders*
C14=/home/rockwolf/\.*rc2

fBackupWeekly()
{
    OLDDIR=/mnt/D/bak/conf/weekly/old
    NEWDIR=/mnt/D/bak/conf/weekly/new
    
    fBackup $OLDDIR $NEWDIR
    echo "conf - weekly backup [OK]"
}

fBackup()
{
    ### remove previous bak-ups
    rm $OLDDIR/*.tar.gz

    ### move current backup from new to old
    mv $NEWDIR/*.tar.gz $OLDDIR

    ### make backup
    tar czf $NEWDIR/rc`date +%Y-%m-%d`.tar.gz $C01
    tar czf $NEWDIR/vim`date +%Y-%m-%d`.tar.gz $C02
    tar czf $NEWDIR/mc`date +%Y-%m-%d`.tar.gz $C03
    tar czf $NEWDIR/local`date +%Y-%m-%d`.tar.gz $C04
    tar czf $NEWDIR/gnupg`date +%Y-%m-%d`.tar.gz $C05
    tar czf $NEWDIR/fontsconfd`date +%Y-%m-%d`.tar.gz $C06
    tar czf $NEWDIR/config`date +%Y-%m-%d`.tar.gz $C07
    tar czf $NEWDIR/cmus`date +%Y-%m-%d`.tar.gz $C08
    tar czf $NEWDIR/authenticate`date +%Y-%m-%d`.tar.gz $C09
    tar czf $NEWDIR/abook`date +%Y-%m-%d`.tar.gz $C10
    tar czf $NEWDIR/Xresources`date +%Y-%m-%d`.tar.gz $C11
    tar czf $NEWDIR/xinitrc`date +%Y-%m-%d`.tar.gz $C12
    tar czf $NEWDIR/reminders`date +%Y-%m-%d`.tar.gz $C13
    tar czf $NEWDIR/rc2`date +%Y-%m-%d`.tar.gz $C14
}

fBackupMonthly()
{
    OLDDIR=/mnt/D/bak/conf/monthly/old
    NEWDIR=/mnt/D/bak/conf/monthly/new
    
    fBackup $OLDDIR $NEWDIR
    echo "conf - monthly backup [OK]"
}


fUsage()
{
    echo "Usage: bu-conf"
    exit 1
}

case $# in
0)
    DOW=`date +%u`
    DOM=`date +%d`
    if [ "$DOW" = "1" ];
    then
        fBackupWeekly
    fi
    if [ "$DOM" = "01" ];
    then
        fBackupMonthly
    fi
    ;;
*)
    fUsage
    ;;
esac
