#!/bin/bash

# Author: Rockwolf
# Date: 19-02-2008
# cpu: This script returns the cpu utilisation in %
#     It uses the following external programs:
#		* mpstat (sysapps/sysstat)
#		* grep
#		* cut
#		* bc

# Get cpu idle percentage from mpstat
IDLE=`mpstat 1 1 | grep Average | sed 's/  */ /g' | cut -d' ' -f10`

#CPU=$(echo "scale=2; 100-$IDLE" | bc)

#echo "$CPU%"
echo "$IDLE%"
