#!/bin/sh

LOG="/var/log/mailcount.log"
SHDIR="/usr/local/sh/linux"

if [ `$SHDIR/mdt 1 | grep messages | cut -d' ' -f4` = "in" ]; then
	echo L: `$SHDIR/mdt 1 | grep messages | cut -d' ' -f1`/`$SHDIR/mdt 1 | grep messages | cut -d' ' -f7` > $LOG
else
	echo L: `$SHDIR/mdt 1 | grep messages | cut -d' ' -f1`/`$SHDIR/mdt 1 | grep messages | cut -d' ' -f4` > $LOG
fi
if [ `$SHDIR/mdt 2 | grep messages | cut -d' ' -f4` = "in" ]; then
	echo T: `$SHDIR/mdt 2 | grep messages | cut -d' ' -f1`/`$SHDIR/mdt 2 | grep messages | cut -d' ' -f7` >> $LOG
else
	echo T: `$SHDIR/mdt 2 | grep messages | cut -d' ' -f1`/`$SHDIR/mdt 2 | grep messages | cut -d' ' -f4` >> $LOG
fi
#>> /var/log/mailcount #`$SHDIR/mdt 2 | grep messages | cut -d' ' -f1`/`$SHDIR/mdt 1 | grep messages | cut -d' ' -f7`
