#!/bin/bash
#mknod /dev/loop0 b 7 0 #only necessary if not already present
dd if=/dev/zero of=/eswap bs=1M count=1024
losetup /dev/loop0 /eswap
mkswap /dev/loop0
swapon /dev/loop0
##emerge openoffice #2.0.3 needed a lot of memory or it would crash
#swapoff /dev/loop0
#losetup -d /dev/loop0
#rm /eswap
