#!/bin/sh
#wmMatrix &
#wmwifi -lc cyan &
#wmdiskmon -p /dev/hda3 -p /dev/hda4 -m -lc cyan &
wmweather -s EBBR -m -b -a& 
wmweather -s EBAW -m -b -a&
#wclock & 
#wmblob & 
#wmfishtime &
pclock &
wmbiffmore 3 &
#wmxres &
wmtop &
wmmemfree & 
#wmDownload &
#wmtimer &
