#!/bin/sh

MINARGS=3
EXITERR=-1

show_error(){
    echo "Usage: mountp <filesystem> <the X in sdX to mount> <mountpoint in /mnt/>."
}

# Checks number of arguments.
case $# in
$MINARGS)
    echo "Executing: mount -t $1 /dev/sd$21 /mnt/$3"
    mount -t $1 /dev/sd$21 /mnt/$3
    echo "Done"
    ;;
*)
    show_error
    exit $EXITERR
    ;;
esac
