#!/bin/sh

MINARGS=1          # Script requires at least 1 argument.
E_BADARGS=65

show_error()
{
	echo
	echo "Shows message and locks the screen."
    echo "Usage: xnotify <message>"
}

# Checks number of arguments.
if [ $# -ne $MINARGS  ]; 
then
	show_error
	exit $E_BADARGS
fi

zenity --warning --text "It is time for $1.\n\n Do you want me to lock up?";
ans=$?;

if [ "$ans" -eq "1" ]
then
	exit 0
else
	#we are leaving, lock screen
	slock
fi
