#!/bin/sh

dd if=/dev/zero of=burnthis.iso bs=1024 count=4589800
mkudffs burnthis.iso
mkdir /mnt/loop
mount -o loop -t udf burnthis.iso /mnt/loop
cp -rv $1 /mnt/loop
umount /mnt/loop
echo "Done."
echo "You can now burn the file burnthis.iso with the command burndvd burnthis.iso"
