#!/bin/sh

shopt -s nullglob
 
cd ~/wall

while true; do
    files=()
    for i in *.jpg *.png *.jpe; do
        [[ -f $i ]] && files+=("$i")
    done
    range=${#files[@]}

    ((range)) && feh --bg-scale "${files[RANDOM % range]}"

    sleep 480m
done
