#!/bin/sh

MINARGS=1
EXITERR=-1

show_error(){
    echo "Usage: umountp <mountpoint in /mnt/>."
}

# Checks number of arguments.
case $# in
$MINARGS)
    echo "Executing: umount /mnt/$1"
    umount /mnt/$1
    echo "Done"
    ;;
*)
    show_error
    exit $EXITERR
    ;;
esac
