#!/bin/sh
TZ=":Europe/Brussels" wmclockmon -lc cyan &#xclock -norender -fg cyan4 -bg black -digital -brief -twentyfour -face one&
#delay 2
#TZ=":Europe/Brussels" #xclock -norender -fg cyan4 -hl cyan -hd cyan -bg black -face one&
#delay 2
TZ=":Australia/Sydney" wmclockmon -lc cyan &#xclock -norender -fg cyan4 -bg black -digital -brief -twentyfour -face two&
#delay 2
#TZ=":Australia/Sydney" #xclock -norender -fg cyan4 -hl cyan -hd cyan -bg black -face two&
#delay 2
TZ=":US/Eastern" wmclockmon -lc cyan &#xclock -norender -fg cyan4 -bg black -digital -brief -twentyfour -face three&
#delay 2
#TZ=":US/Eastern" #xclock -norender -fg cyan4 -hl cyan -hd cyan -bg black -face three&
